### ISSUE TITLE
Time interval

### ISSUE THREAD

**Issue by Huh** [MZimova/Foxes-molts-analysis#3]
For the fox analysis what time interval makes the most sense given the way the data was collected?

I can imagine doing weekly or monthly.

Thanks,
Josh

**Comment by MZimova** [comment]
The data was analyzed from pictures taken by motion triggered camera traps installed by the fox dens- so I'd say we can assign intervals completely arbitrarily. If we can do weeks, it would be great. The distribution is totally uneven in time though as during some periods of the year (summer) the foxes were away from the dens so there are disproportionately fewer photos then. 
Let's try weekly and if that doesn't work let's try biweekly. Thanks!
